object:
  metaphor_set: [["蝶", "踊り子"]]
  assoc_file: "tint_prj/data/three_metaphor_assoc_data.csv"
  image_file: "tint_prj/data/three_metaphor_images.csv"
  out_dir: "tint_prj/out/"
  NN: 0
  steps: 1000
  search_method: "deterministic"
  softmax_beta: 1.0
  seed: 1234
  verbose: true

triangle:
  metaphor_set: [["蝶", "踊り子"]]
  assoc_file: "tint_prj/data/three_metaphor_assoc_data.csv"
  image_file: "tint_prj/data/three_metaphor_images.csv"
  out_dir: "tint_prj/out/"
  NN: 0
  steps: 1000
  search_method: "deterministic"
  softmax_beta: 1.0
  seed: 1234
  verbose: true